baseURL = "https://skyseraph.github.io/"
languageCode = "zh-CN"
title = "SkySeraph"
theme = "skyseraph"
defaultContentLanguage = "zh"
enableRobotsTXT = true
enableEmoji = true
paginate = 10

[params]
  author = "SkySeraph"
  description = "AI for All"
  keywords = ["AI/LLM", "APP/Android", "架构师", "SkySeraph"]
  avatar = "/images/skyseraph.png"
  github = "skyseraph"
  email = ""
  since = 2015

  imageBase = "https://cdn.jsdelivr.net/gh/skyseraph/skyseraph.github.io@main/static/images"

  [params.giscus]
    enabled = true
    repo = "skyseraph/skyseraph.github.io"
    repoID = "R_kgDOJNG05w"
    category = "Announcements"
    categoryID = "DIC_kwDOJNG0584C7aUl"
    mapping = "pathname"
    theme = "light"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "专栏"
    url = "/series/"
    weight = 3
  [[menu.main]]
    name = "作品"
    url = "/projects/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
  [[menu.main]]
    name = "友链"
    url = "/links/"
    weight = 6

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = true
    lineNumbersInTable = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
